name: clima_tempo
description: Um aplicativo de previsão do tempo que exibe informações para diferentes cidades.

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0

  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/sol.png
    - images/nublado.png
    - images/chuva.png
    - images/avatar.jpg
    - images/Fundo_home.png
    - images/fundo_menu.jpg
    - images/fundo_city.jpeg
    - images/temperatura_frio.png
    - images/temperatura_quente.png
    - images/sol_nuvens.png
    - images/trovoada.png
    - images/sol_chuva.png
    - images/loading.gif
    - images/nevoeiro.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 700